### ISSUE TITLE
Error: Template file not found

### ISSUE THREAD

**Issue by javad-zobeidi** [FJSolutions/adonis-mongoose#1]
when is use this comment i get this error 

`(node:6644) UnhandledPromiseRejectionWarning: Error: Template file not found: ~\@fjsolutions\adonis-mongoose\build\templates\database.ts.mustache
    at read (~\smpltmpl\index.js:21:10)
    at templateFromFile (~\smpltmpl\index.js:80:15)
    at Object.apply (~\mrm-core\src\formats\template.js:33:14)
    at TemplateLiteralFile.apply (~\@adonisjs\sink\src\Files\Formats\TemplateLiteral.js:43:26)
    at TemplatesManager.copyTemplateFor (~\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:98:18)
    at ~\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:114:41
    at Array.forEach (<anonymous>)
    at TemplatesManager.copyTemplatesFor (~\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:114:14)
    at ~\@adonisjs\sink\src\Tasks\TemplatesManager\index.js:132:18
    at Array.forEach (<anonymous>)
(node:6644) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:6644) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Error: Cannot find module '@zakodium/adonis-mongodb/lib/commands'
Require stack:
- ~\noop.js

1 resolveFileName
  ~\resolve-from\index.js:29

2 resolveFrom
  ~\resolve-from\index.js:43

3 Object.module.exports [as default]
  ~\resolve-from\index.js:46

4 Object.resolveFrom
  ~\@poppinss\utils\build\src\resolveFrom.js:25

5 ManifestGenerator.loadCommand
  ~\@adonisjs\ace\build\src\Manifest\Generator.js:35

6 anonymous
  ~\@adonisjs\ace\build\src\Manifest\Generator.js:55

7 ManifestGenerator.loadCommands
  ~\@adonisjs\ace\build\src\Manifest\Generator.js:54

8 ManifestGenerator.generate
  ~\@adonisjs\ace\build\src\Manifest\Generator.js:63`

**Comment by FJSolutions** [comment]
Thank you for reporting this. Can you tell me what you were doing when this error occurred?

**Comment by javad-zobeidi** [comment]
when I want to create a model

**Comment by FJSolutions** [comment]
I’ve updated the packages to the latest Adonis versions and ensured that the Model Template is present, and republished to NPM

 

Francis Judge

072 564 7502
